/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPokedexIndexRouteImport } from './routes/_authenticated/pokedex/index'
import { Route as AuthenticatedPokedexNameRouteImport } from './routes/_authenticated/pokedex/$name'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPokedexIndexRoute =
  AuthenticatedPokedexIndexRouteImport.update({
    id: '/pokedex/',
    path: '/pokedex/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPokedexNameRoute =
  AuthenticatedPokedexNameRouteImport.update({
    id: '/pokedex/$name',
    path: '/pokedex/$name',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/pokedex/$name': typeof AuthenticatedPokedexNameRoute
  '/pokedex/': typeof AuthenticatedPokedexIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/pokedex/$name': typeof AuthenticatedPokedexNameRoute
  '/pokedex': typeof AuthenticatedPokedexIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/_authenticated/pokedex/$name': typeof AuthenticatedPokedexNameRoute
  '/_authenticated/pokedex/': typeof AuthenticatedPokedexIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/home' | '/login' | '/pokedex/$name' | '/pokedex/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home' | '/login' | '/pokedex/$name' | '/pokedex'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/home'
    | '/login'
    | '/_authenticated/pokedex/$name'
    | '/_authenticated/pokedex/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pokedex/': {
      id: '/_authenticated/pokedex/'
      path: '/pokedex'
      fullPath: '/pokedex/'
      preLoaderRoute: typeof AuthenticatedPokedexIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pokedex/$name': {
      id: '/_authenticated/pokedex/$name'
      path: '/pokedex/$name'
      fullPath: '/pokedex/$name'
      preLoaderRoute: typeof AuthenticatedPokedexNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedPokedexNameRoute: typeof AuthenticatedPokedexNameRoute
  AuthenticatedPokedexIndexRoute: typeof AuthenticatedPokedexIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPokedexNameRoute: AuthenticatedPokedexNameRoute,
  AuthenticatedPokedexIndexRoute: AuthenticatedPokedexIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
