/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PokedexIndexRouteImport } from './routes/pokedex/index'
import { Route as PokedexNameRouteImport } from './routes/pokedex/$name'
import { Route as AuthPathnameRouteImport } from './routes/auth.$pathname'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PokedexIndexRoute = PokedexIndexRouteImport.update({
  id: '/pokedex/',
  path: '/pokedex/',
  getParentRoute: () => rootRouteImport,
} as any)
const PokedexNameRoute = PokedexNameRouteImport.update({
  id: '/pokedex/$name',
  path: '/pokedex/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/pokedex/$name': typeof PokedexNameRoute
  '/pokedex/': typeof PokedexIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/pokedex/$name': typeof PokedexNameRoute
  '/pokedex': typeof PokedexIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/pokedex/$name': typeof PokedexNameRoute
  '/pokedex/': typeof PokedexIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/home' | '/auth/$pathname' | '/pokedex/$name' | '/pokedex/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home' | '/auth/$pathname' | '/pokedex/$name' | '/pokedex'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/auth/$pathname'
    | '/pokedex/$name'
    | '/pokedex/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  AuthPathnameRoute: typeof AuthPathnameRoute
  PokedexNameRoute: typeof PokedexNameRoute
  PokedexIndexRoute: typeof PokedexIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokedex/': {
      id: '/pokedex/'
      path: '/pokedex'
      fullPath: '/pokedex/'
      preLoaderRoute: typeof PokedexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokedex/$name': {
      id: '/pokedex/$name'
      path: '/pokedex/$name'
      fullPath: '/pokedex/$name'
      preLoaderRoute: typeof PokedexNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  AuthPathnameRoute: AuthPathnameRoute,
  PokedexNameRoute: PokedexNameRoute,
  PokedexIndexRoute: PokedexIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
